Final_Project-main/my_asset_project/assets/views.py
from flask import app, render_template, url_for, request, redirect, Blueprint, flash, session
from sqlalchemy import desc

from my_asset_project import db
from my_asset_project.assets.forms import BulkUploadForm, AddNewAssetForm, AssetSearchForm,EditAssetForm, MasterDropdownForm, UserLifeCycle
import pandas as pd
from datetime import date
from my_asset_project.models import Asset_Details,Asset_Status_Details,Asset_User_Mapping,Asset_Trail,User_Details,MasterDropdown, Asset_log
from sqlalchemy import create_engine, or_
from my_asset_project import app
from flask import jsonify, request
from sqlalchemy.sql import column
import traceback



import os
from flask import send_from_directory

add_new_asset = Blueprint('add_asset', __name__)
asset_upload = Blueprint('assets', __name__)
asset_search = Blueprint('search_asset', __name__)
#edit_asset = Blueprint('edit_asset', __name__)
#Edit_asset = Blueprint('assets', __name__)
asset_blueprint = Blueprint('asset_blueprint', __name__)#####EDIT ASSET#######
view_asset=Blueprint('view_asset', __name__)
get_asset_number = Blueprint('get_asset_number', __name__)
asset_lifecycle = Blueprint('asset_lifecycle', __name__)
set_asset_id = Blueprint('set_asset_id', __name__)



#Bulk Upload
@asset_upload.route('/bulk_upload', methods=['POST', 'GET'])
def bulk_upload():
    form = BulkUploadForm()

    if form.validate_on_submit():
        excel_file = form.excel_file.data
        df = pd.read_excel(excel_file) #Using pandas to read excel file
        engine = create_engine('mysql+pymysql://root:santhu01@localhost/ams', echo=False) #Creates engine using sqlalchemy to insert data in mysql
        # Define the columns for table1 and table2
        table1_columns = ['asset_number', 'product_category', 'product_name', 'model_version', 'manufacturer', 'asset_status', 'user_name', 'employee_id', 'location', 'other_location', 'user_email', 'contact', 'company', 'other_company', 'assigned_start_date', 'in_stock_start_date', 'not_working_start_date', 'end_of_life_start_date', 'retain_date', 'retain_amount', 'transfer_date', 'record_insertion_date', 'transferred_amount', 'transferred_from', 'transferred_to', 'disposed_date', 'disposed_amount', 'asset_category', 'oem_serial_number', 'system_host_name', 'ip_address', 'AIC_office', 'oem_asset_warranty', 'oem_warranty_expiry_date', 'insurance_coverage', 'insurance_company',  'policy_number', 'insured_amount', 'start_date', 'end_date', 'supplier_name', 'supplier_contact', 'supplier_location', 'supplier_email', 'incident_id', 'remarks', 'payment_done', 'payment_date', 'voucher_number','device_type', 'desk_lap_os', 'desk_lap_hdd_type', 'desk_lap_hdd_size', 'desk_lap_ram_type', 'desk_lap_ram_size', 'desk_lap_ram_frequency', 'desk_lap_ram_expandable', 'desk_lap_ram_slots', 'desk_lap_hdmi_port', 'desk_lap_display_size', 'desk_lap_graphics_card_size', 'desk_lap_graphics_card_version', 'printer_type', 'printing_type', 'printer_toner_name', 'printer_connectivity', 'hdd_size', 'hdd_type', 'hdd_connectivity', 'tab_os', 'tab_storage', 'tab_ram_size', 'tab_display_size', 'tab_stylus', 'tab_connectivity', 'monitor_display_size', 'monitor_hdmi_port', 'monitor_speaker', 'ups_capacity', 'ups_amc', 'ups_start_date', 'ups_end_date', 'source_of_purchase', 'contract_id','invoice_id', 'invoice_amount', 'invoice_date', 'invoice_upload', 'other_insurance']
        table2_columns = ['asset_status', 'employee_id', 'user_name', 'user_email', 'user_contact', 'company', 'other_company', 'location', 'other_location', 'retain_date', 'retained_end_date', 'retain_amount', 'transfer_date', 'transferred_end_date', 'in_stock_start_date', 'in_stock_end_date', 'assigned_start_date', 'assigned_end_date', 'not_working_start_date', 'not_working_end_date', 'end_of_life_start_date', 'end_of_life_end_date', 'transferred_amount', 'transferred_from', 'transferred_to', 'disposed_date', 'disposed_end_date', 'disposed_amount', 'record_insertion_date']
        
        # Create DataFrames for table1 and table2
        table1_df = df[table1_columns]
        table2_df = df[table2_columns]

        # Insert data into table1
        table1 = "asset_details"
        table1_df.to_sql(table1, engine, if_exists='append', index=False)

        # Insert data into table2
        table2 = "asset_history"
        table2_df.to_sql(table2, engine, if_exists='append', index=False)

        engine.dispose()
    return render_template('bulk_upload.html', form=form)

@get_asset_number.route('/get_last_asset', methods=['GET'])
def get_last_asset():
    # Extract product_category and AIC_office from the request
    product_category = request.args.get('product_category')
    AIC_office = request.args.get('AIC_office')
    
    if AIC_office in ["Statesman House", "East Kidwai Nagar", "Parsvnath Capital Towers"]:
        # If AIC_office is one of the specified values, fetch the maximum asset number
        max_asset = Asset_Details.query.filter(Asset_Details.product_category == product_category, 
                                               or_(Asset_Details.AIC_office == "Statesman House",
                                                   Asset_Details.AIC_office == "East Kidwai Nagar",
                                                   Asset_Details.AIC_office == "Parsvnath Capital Towers"))\
                                      .order_by(Asset_Details.asset_number.desc())\
                                      .first()
        
        if max_asset:
            last_asset_number = int(max_asset.asset_number.split("/")[-1])
        else:
            last_asset_number = 0  # Handle cases where no previous asset exists
    else:
        # If AIC_office is not one of the specified values, fetch as before
        last_asset = Asset_Details.query.filter_by(product_category=product_category, AIC_office=AIC_office)\
                                       .order_by(Asset_Details.id.desc())\
                                       .first()

        if last_asset:
            last_asset_number = int(last_asset.asset_number.split("/")[-1])
        else:
            last_asset_number = 0  # Handle cases where no previous asset exists
    print(last_asset_number, "Last Asset")
    # Return the last asset number as JSON
    return jsonify({'lastNumber': last_asset_number})


# Function to generate asset numbers
def generate_asset_number(product_category, AIC_office, AICOfficePrefixes, productCategoryPrefixes):
    with app.app_context():
        # Check if the provided AIC office and product category are in the prefixes dictionaries
        if AIC_office in AICOfficePrefixes and product_category in productCategoryPrefixes:
            AIC_prefix = AICOfficePrefixes[AIC_office]
            category_prefix = productCategoryPrefixes[product_category]

            if AIC_office in ["HO Statesman", "HO Kidwai Nagar", "HO Parsvnath"]:
                # If AIC_office is one of the specified values, fetch the maximum asset number
                max_asset = Asset_Details.query.filter(
                    Asset_Details.product_category == product_category,
                    or_(Asset_Details.AIC_office == "HO Statesman",
                        Asset_Details.AIC_office == "HO Kidwai Nagar",
                        Asset_Details.AIC_office == "HO Parsvnath")
                ).order_by(Asset_Details.asset_number.desc()).first()

                if max_asset:
                    # Extract the last asset number and increment it by 1
                    last_asset_number = int(max_asset.asset_number.split("/")[-1])
                    new_asset_number = last_asset_number + 1
                else:
                    # If no previous asset exists for this combination, start with 1
                    new_asset_number = 1
            else:
                # If AIC_office is not one of the specified values, fetch as before
                last_asset = Asset_Details.query.filter_by(product_category=product_category, AIC_office=AIC_office)\
                    .order_by(Asset_Details.id.desc()).first()

                if last_asset:
                    # Extract the last asset number and increment it by 1
                    last_asset_number = int(last_asset.asset_number.split("/")[-1])
                    new_asset_number = last_asset_number + 1
                else:
                    # If no previous asset exists for this combination, start with 1
                    new_asset_number = 1

            # Format the new asset number and construct the asset number string
            asset_number = f'AIC/{AIC_prefix}/{category_prefix}/{new_asset_number:02d}'
            return asset_number
        else:
            return None  # Handle cases where prefixes are not found


from sqlalchemy.sql import column

@app.route('/get_code', methods=['GET'])
def get_code():
    product_category = request.args.get('product_category')
    AIC_office = request.args.get('AIC_office')
    print(f"Product category: {product_category}")
    print(f"AIC Office: {AIC_office}")

    # Query the database to fetch the code based on the selected product_category
    result_product_category = MasterDropdown.query.filter_by(category='Product Category', choice=product_category).with_entities(column('code')).first()

    # Query for AIC Office
    result_AIC_office = MasterDropdown.query.filter_by(category='AIC Office', choice=AIC_office).with_entities(column('code')).first()

    # Unpack the result to get the actual value
    result_product_category = result_product_category[0] if result_product_category else None
    result_AIC_office = result_AIC_office[0] if result_AIC_office else None
    
    print(f"Result for Product category code: {result_product_category}")
    print(f"Result for AIC Office code: {result_AIC_office}")

    if result_product_category is not None and result_AIC_office is not None:
        response_data = {
            'code_product_category': result_product_category,
            'code_AIC_office': result_AIC_office
        }

Final_Project-main/my_asset_project/core/views.py
from flask import render_template, request, Blueprint, session, redirect, url_for
from my_asset_project.assets.forms import AssetSearchForm


core = Blueprint('core',__name__)

############################Core page for IT and Estb#########################
@core.route('/')
def index():
    #form = AssetSearchForm()
    log_content=""
    if 'name' not in session:
        return redirect(url_for('users.login'))
    else:
        alert_message = request.args.get('alert_message')
        log_file_path = 'app.log'  
        with open(log_file_path, 'r') as file:
            log_content = file.read()
            print(log_content)
        return render_template('index.html',alert_message=alert_message, log_content=log_content)
    return render_template('index.html')
     

Final_Project-main/my_asset_project/users/views.py
from flask import render_template, url_for, request, redirect, Blueprint, flash, session
from flask_login import login_user, logout_user
from my_asset_project import db, app
from my_asset_project.models import User
from my_asset_project.users.forms import RegistrationForm, LoginForm
import pdb
import json
from functools import wraps
import logging
from logging.handlers import RotatingFileHandler
from flask import jsonify
from werkzeug.security import check_password_hash, generate_password_hash

 #Import the 'flash' function from Flask
from flask import render_template, flash, redirect, url_for, request

from functools import wraps
from flask import session, redirect, url_for


# def superuser_required(f):
#     @wraps(f)
#     def decorated_function(*args, **kwargs):
#         if session.get('role') == 'Super':
#             return f(*args, **kwargs)
#         else:
#             # Handle unauthorized access here, such as redirecting or rendering an error page
#             print("No Access")
#             # return render_template('/unauthorized.html')
#     return decorated_function

users = Blueprint('users', __name__)

#register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
   
    if form.validate_on_submit():
        
        user = User(AIC_office = form.AIC_office.data,
                    user_email = form.user_email.data,
                    password= form.password.data)
        db.session.add(user)
        db.session.commit()
        #flash('Thanks for Registration!')
        #app.logger.info('New user added: %s by %s', form.user_email.data, session.get('name'))

        return redirect(url_for('users.login'))
    
    return render_template('add-user.html', form = form)


 # Your existing login route
@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    success_modal = False
    print(form.user_email.data, form.password.data, "1234")
    print("Form submitted:", request.method)
    print("Form validated:", form.validate_on_submit())
    print("Form errors:", form.errors)

    #-----------
    if request.method=='POST' and form.validate():
        user = User.query.filter_by(user_email = form.user_email.data).first()
        print(check_password_hash(user.password_hash, form.password.data))
        if user and check_password_hash(user.password_hash, form.password.data):
            print("Yes")
            session['name'] = user.domain_name
            session['location']=user.AIC_office
            success_modal = True
            # Flash the message for use with templates
            #flash('Log in Success!')

            # Display an alert using JavaScript
        
            next = request.args.get('next')
            print(next, 'next')
            if next == None or not next[0]=='/':
                next = url_for('core.index')
            return redirect(next)
        else:
            flash("Email ID or Password is Incorrect!", "info")
            return render_template('login.html', form=form,success_modal=success_modal)     
              
    return render_template('login.html', form=form, success_modal=success_modal)

    # return render_template('login.html', form=form,success_modal=success_modal)

    #-----------
#     if form.validate_on_submit():
#          user = User.query.filter_by(user_email = form.user_email.data).first()
#          if user is not None and user.check_password(form.password.data):
#              session['role'] = user.role
#              session['name'] = user.domain_name
#              session['permissions']=user.Permissions
#              session['dept']=user.department
#              session['location']=user.AIC_office
#              success_modal = True
#              # Flash the message for use with templates
#              #flash('Log in Success!')

#              # Display an alert using JavaScript
            
#              next = request.args.get('next')

#              if next == None or not next[0]=='/':
#                  next = url_for('core.index')
#              return redirect(next)
#          else:
#             flash("Email ID or Password is Incorrect!", "info")
#             return render_template('login.html', form=form,success_modal=success_modal)


#     return render_template('login.html', form=form,success_modal=success_modal)

@users.route("/add-user", methods=['GET', 'POST'])
def add_user():
    form = RegistrationForm()
    existing_user = ""
    form.set_choices()
    print("password", form.password.data)

    if request.method == 'POST' and form.validate():
        existing_user = User.query.filter_by(user_email=form.user_email.data).first()
        if existing_user:
            flash('Email already exists. Please use a different email.', "info")
        else:
            user = User(
                AIC_office=form.AIC_office.data,
                user_email=form.user_email.data,
                domain_name=form.domain_name.data,
                password_hash=form.password.data  # ✅ use consistent name
            )

            db.session.add(user)
            db.session.commit()
            flash('User Added Successfully!', "info")
            app.logger.info('New user added: %s by %s', form.user_email.data, session.get('name'))

    return render_template('add-user.html', form=form)


#logout
@users.route("/logout")
def logout():
    session.pop('name', None)
    session.pop('role', None)
    session.pop('dept', None)
    session.clear()
    logout_user()
    return redirect(url_for("users.login"))

 

@users.route("/get-user", methods=['GET'])
def get_user():
    user = User.query.all()
    r = [u.user_email for u in user]
    print("users",)


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'name' not in session:
            return redirect(url_for('users.login'))
        return f(*args, **kwargs)
    return decorated_function

Final_Project-main/my_asset_project/templates/access-denied.html
<style>
    .h6-format {
        color: red;
        font-weight: 100;
        text-decoration: none;
        /*underline;*/
    }
    .bc-color{
        background-color: #100;
        color: white;
    }
</style>
<div class="w3-display-middle bc-color">
    <h1 class="w3-jumbo w3-animate-top w3-center" style="color: red;"><code>Access Denied</code></h1>
    <hr class="w3-border-white w3-animate-left" style="margin:auto;width:50%">
    <h3 class="w3-center w3-animate-right">You dont have permission to view this site.</h3>
    <h3 class="w3-center w3-animate-zoom">🚫🚫🚫🚫</h3>
    <h6 class="w3-center w3-animate-zoom"><strong>Error Code</strong>: 403 forbidden</h6>
</div>

Final_Project-main/my_asset_project/templates/add-user.html
{% extends 'base1.html' %}
{% block title %}Add User Page{% endblock %}
{% block bodyContent %}

<style>
    h2 {
        text-align: center;
    }
    .awesome-header {
        font-size: 25px;
        text-align: center;

        color: green;
        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
    }
</style>
<div class="container">
    <div class=" row justify-content-center">
        
        <div class="col-sm-6 mt-4">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                    {{ message }}
                    </div>
                {% endfor %}
            {% endwith %}
            <div class="text-center">
                <hr>
                <h3 class="awesome-header">Add User</h3>
                <p style="color: darkgoldenrod;">Add a User by Completing the Form below</p>
                <hr>
            </div>
            <form method="POST" action="/add-user">
                {{ form.hidden_tag() }}

                <div class="form-group">
                    <label for="{{ form.AIC_office.id }}">AIC Office:<span style="color: red;">*</span></label>
                    {{ form.AIC_office(class="form-control", id=form.AIC_office.id) }}
                </div>
                <div class="form-group">
                    <label for="{{ form.domain_name.id }}">Domain Name:<span style="color: red;">*</span></label>
                    {{ form.domain_name(class="form-control", id=form.domain_name.id) }}
                </div>
                <div class="form-group">
                    <label for="{{ form.user_email.id }}">{{ form.user_email.label }}<span style="color: red;">*</span></label>
                    {{ form.user_email(class="form-control", id=form.user_email.id) }}
                </div>
                <div class="form-group">
                    <label for="{{ form.password.id }}">{{ form.password.label }}<span style="color: red;">*</span></label>
                    {{ form.password(class="form-control", id=form.password.id) }}
                </div>
            
                <div class="form-group">
                    <label for="{{ form.pass_confirm.id }}">{{ form.pass_confirm.label }}<span style="color: red;">*</span></label>
                    {{ form.pass_confirm(class="form-control", id=form.pass_confirm.id) }}
                </div>
                {{ form.submit(class="btn btn-primary") }}
                
            </form>            
        </div>
    </div>
  
</div>
<script>
    function validateEmail(event) {
    const emailInput = document.getElementById('user_email').value;
    const emailError = document.getElementById('emailError');
    const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailPattern.test(emailInput)) {
        emailError.textContent = 'Please enter a valid email address';
        return false; // Prevent form submission
    } 
    else {
        emailError.textContent = ''; // Clear any previous error message
        return true; // Allow form submission
    }
}

</script>

<style>
    .h6-format {
        color: red;
        font-weight: 100;
        text-decoration: none;
        /*underline;*/
    }
    .bc-color{
        background-color: #100;
        color: white;
    }
</style>

{% endblock %}

Final_Project-main/my_asset_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <!-- <script type= "text/javascript" src="{{ url_for('static', filename='mainjs/edit_asset.js') }}"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</head>
<body>
    <ul class="nav bg-dark" style="padding: 14px;">
        <img src=".\static\images\aic_logo.png" alt="Logo" style="max-height: 100px; margin-right: 10px; border-radius: 10px;">
        <li class="nav-link">
            <a href="{{url_for('core.index')}}" class="text-white" style="font-size: 20px;">Home</a>
        </li>

        {%  if current_user.is_authenticated %}

        <li class="nav-link">
            <a href="{{url_for('users.logout')}}" class="text-white" style="position: absolute; top: 0; right: 0; margin: 16px; padding: 8px; border-radius: 12px; background-color:rgb(70, 70, 179);">Log Out</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('add_asset.add_asset')}}" class="text-white" style="font-size: 20px;">Add New Asset</a>
        </li>
        
        <!-- <li class="nav-link">
            <a href="{{url_for('assets.bulk_upload')}}" class="text-white" style="font-size: 20px;"> Bulk Upload Asset Data</a>
        </li> -->
        <li class="nav-link">
            <a href="{{ url_for('asset_lifecycle.get_asset_life_cycle') }}" class="text-white" style="font-size: 20px;">Asset Life Cycle</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('master_dropdown.master_dropdown_view')}}" class="text-white" style="font-size: 20px;"> Master Dropdown</a>
        </li>
        <!-- Corrected base.html template -->
<!-- ... other code ... -->


<!-- ... other code ... -->


        <li class="nav-link">
            <a href="{{url_for('users.login')}}" class="text-white" style="position: absolute; top: 0; right: 0; margin: 16px; padding: 8px; border-radius: 12px; background-color:rgb(70, 70, 179);">Log In</a>
        </li>

        <li class="nav-link">
            <a href="{{url_for('users.register')}}" class="text-white" style="font-size: 20px;">Register</a>
        </li>
        
        

        {% endif %}
    </ul>

    <div class="container">
        {% block content %}

        {% endblock %}

    </div>

    <script src="{{ url_for('static', filename='mainjs/edit_asset.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='mainjs/sweetalert.js') }}"></script>

    <!-- <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11" ></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js" integrity="sha512-AA1Bzp5Q0K1KanKKmvN/4d3IRKVlv9PYgwFPvm32nPO6QS8yH1HO7LbgB1pgiOxPtfeg5zEn2ba64MUcqJx6CA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> -->
</body>
</html>

Final_Project-main/my_asset_project/templates/bulk_upload.html
{% extends "base1.html" %}
{% block bodyContent %}
    <style>
        .awesome-header {
        font-size: 25px;
        text-align: center;

        color: green;
        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
    }

    .container1 {
        padding: 0 18px;
        overflow: hidden;
    }

    .upload-container {
        background-color: #ffffff;
        border-radius: 20px;
        padding: 50px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        text-align: center;
    }

    label {
        font-size: 18px;
    }

    input[type="file"] {
        display: block;
        margin: 10px auto;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #f9f9f9;
        cursor: pointer;
    }

    input[type="submit"] {
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        background-color: #007bff;
        color: white;
        font-size: 16px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    input[type="submit"]:hover {
        background-color: #0056b3;
    }

    </style>

    <div class="container">
        <div class="row">
            <div class="container" style="text-align: center;">
                    <div class="card-body">
                        <a href="/search_assets"><button type="button" class="btn btn-success">Search Assets</button></a>
                        <a href="/add_asset"><button type="button" class="btn btn-success">Add New Asset</button></a>
                        <a href="/asset_life_cycle"><button type="button" class="btn btn-success">Asset Life Cycle</button></a>
        
                    </div>
            </div>
        </div>
    </div>


<div class="container">
    <div class="text-center">
        <hr>
        <h3 class="awesome-header">Bulk Upload Assets</h3>
        <p style="color: darkgoldenrod;">Efficiently and Effortlessly Bulk Upload Assets by Uploading the Excel File below</p>
        <hr>
    </div>
    <div class="upload-container">
        <div class="card">
            <div class="card-body">
                <div class="form-group">
                    <div class="container1">
                        <form class="flex-form" id="form-fields" method="POST" enctype="multipart/form-data">
                            {{ form.csrf_token }}
                            {{ form.hidden_tag() }}
                            <div>{{ form.excel_file.label }}</div>
                            <div>{{ form.excel_file }}</div>
                            <div>{{ form.submit }}</div>
                        </form>
                    </div>
                </div>
            </div>
        </div>               
    </div>
</div>

<style>
    .h6-format {
        color: red;
        font-weight: 100;
        text-decoration: none;
        /*underline;*/
    }

</style>
<br>

{% endblock %}

Final_Project-main/my_asset_project/templates/index.html
{% extends "base1.html" %}
{% block bodyContent %}

<section class="vh-100" style="background-color: #eee;">
    <div class="container py-5">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-12">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body">
              <div class="mt-3 mb-4 text-center">
                <img src="/static/images/user-icon-placeholder.png"
                  class="rounded-circle img-fluid" style="width: 100px;padding: 2px;
    border: 2px solid #28a745;" />
              </div>
              <h4 class="mb-2 text-center">Welcome, {{ session.get('name') }}</h4>      
              <div class="container">
                <div class="col-md-12">
                    <!-- <p class="awesome-header" style="font-size: 18px;">Asset Permissions</p>   -->
                        <a href="/search_assets">
                            <button type="button" class="btn btn-success">Search</button>
                        </a>  
                    <a href="/add_asset">
                        <button type="button" class="btn btn-success">Add</button>
                    </a>  
                <!-- <a href="/bulk_upload">
                    <button type="button" class="btn btn-success">Bulk Upload</button>
                </a>   -->
            <a href="/asset_life_cycle">
                <button type="button" class="btn btn-success">Life Cycle</button>
            </a>  
                    <!-- Add other conditions based on the available permissions for IT Assets -->
                </div>
                <br>
            
                </div>
                <br>

                <!-- <div class="col-md-12">
                  <p class="awesome-header" style="font-size: 18px;">Logs</p>
                  <div class="log-container" style="height: 300px; overflow-y: auto;">
                      <pre>{{ log_content }}</pre>
                  </div>
              </div> -->
              

            </div>
            </div>
          </div>
  
        </div>
      </div>
    </div>
  </section>

{% endblock %}

Final_Project-main/my_asset_project/templates/login.html
{% extends "base1.html" %}
{% block bodyContent %}
<style>
    .awesome-header {
      font-size: 25px;
      /* Adjust the font size as needed */
      /* color: #336699; */
      /* Change the color to your preference */
      color: green;
      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
      /* Add a subtle text shadow */
      /* Additional styling can be applied, such as font-family, padding, margin, etc. */
    }
</style>
<!-- <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}"> -->
<div class="container" style="margin-top: 2%; ">
    <h2 class="awesome-header text-center">AMS Login Portal</h2>
    <hr style="border-top: 1px solid green;">
    <div class="row justify-content-center" style="padding: 10px;">
        <div class="col-md-6" style="padding: 50px; border-radius: 10px;border: 2px solid green">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                {{ message }}
                </div>
            {% endfor %}
            {% endwith %}
            <form method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    <label for="{{ form.user_email.id }}">{{ form.user_email.label }}</label>
                    {{ form.user_email(class="form-control", id=form.user_email.id) }}
                </div>
                <div class="form-group">
                    <label for="{{ form.password.id }}">{{ form.password.label }}</label>
                    {{ form.password(class="form-control", id=form.password.id) }}
                </div>
                {{ form.submit(class="btn btn-success") }}
            </form>
            
            </div>
        </div>
    </div>
</div>






{% endblock %}